name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: SoumiliPal3
          outputs: |
            ./output/github-contribution-grid-snake.svg

      - name: Pull latest changes (fix non-fast-forward)
        run: git config --global user.name "GitHub Actions" && \
             git config --global user.email "actions@github.com" && \
             git pull origin main --rebase

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: Generate snake animation
          add: output/github-contribution-grid-snake.svg
          push: true
